// #namespace TFLV::Upgrade;
// #debug off;

class TFLV_Upgrade_DecoyFlares : TFLV_Upgrade_BaseUpgrade {
  // Range within which we distract enemy shots.
  uint FlareRange(uint level) {
    return bonsai_stat_flare_base_range * bonsai_stat_flare_decay**(level-1);
  }

  override void OnProjectileCreated(Actor player, Actor new_shot) {
    // Find nearby seekers and redirect them at this projectile.
    let radius = FlareRange(self.level);
    ThinkerIterator it = ThinkerIterator.Create("Actor", Thinker.STAT_DEFAULT);
    Actor shot;
    while (shot = Actor(it.next())) {
      if (!shot || !shot.bSEEKERMISSILE || shot.tracer != player || player.Distance3D(shot) < radius) {
        continue;
      }
      shot.tracer = new_shot;
      shot.target = player;
    }
  }

  override bool IsSuitableForWeapon(TFLV_WeaponInfo info) const {
    return info.IsSlowProjectile();
  }

  override void GetTooltipFields(Dictionary fields, uint level) {
    fields.insert("flare-range", AsMeters(FlareRange(level)));
  }
}
