// The fire elemental upgrade tree.
//
// APPRENTICE: INCENDIARY SHOTS
// Burns enemies down to a certain % of health.
// More stacks increase both the burn rate, and the minimum %.
// Stack application depends on damage dealt.
// Leveling increases the softcap.
//
// JOURNEYMAN: BURNING TERROR
//
// Reduces the health % at which fire stops burning. Cannot reduce it to 0 --
// diminishing returns.
//
// MASTER: CONFLAGRATION
// Enemies with sufficient fire stacks on them will spread them to nearby enemies.
// More stacks increases the cap for spread fire.
// Higher levels increase the spread speed and radius.
//
// MASTER: INFERNAL KILN
// Attacking burning enemies gives you a temporary damage/resistance bonus.
// #namespace TFLV::Upgrade;
// #debug off

// Fire will try to do this proportion of the target's health in damage.
const BASE_FIRE_FACTOR = 0.5;
const HEAT_FACTOR = 0.9;
const DAMAGE_PER_STACK = 4.0; // per dot tick, so multiply by 5 to get DPS

class TFLV_Upgrade_IncendiaryShots : TFLV_Upgrade_ElementalUpgrade {
  override TFLV_Upgrade_UpgradeElement Element() { return TFLV_Upgrade_ELEM_FIRE; }
  override void OnDamageDealt(Actor player, Actor shot, Actor target, int damage) {
    TFLV_Upgrade_Dot.GiveStacks(player, target, "TFLV_Upgrade_FireDot", damage * bonsai_stat_fire_stack_rate, level);
  }

  override void GetTooltipFields(Dictionary fields, uint level) {
    fields.insert("stacks", AsPercent(level * bonsai_stat_fire_stack_rate));
    fields.insert("softcap", ""..level);
    fields.insert("cutoff", AsPercent(bonsai_stat_fire_cutoff));
  }
}

class TFLV_Upgrade_BurningTerror : TFLV_Upgrade_DotModifier {
  override TFLV_Upgrade_UpgradeElement Element() { return TFLV_Upgrade_ELEM_FIRE; }
  override string DotType() { return "TFLV_Upgrade_FireDot"; }

  override void ModifyDot(Actor player, Actor shot, Actor target, int damage, TFLV_Upgrade_Dot dot_item) {
    TFLV_Upgrade_FireDot(dot_item).terror = level;
  }

  override bool IsSuitableForWeapon(TFLV_WeaponInfo info) const {
    return HasIntermediatePrereq(info, "TFLV_Upgrade_IncendiaryShots");
  }

  override void GetTooltipFields(Dictionary fields, uint level) {
    fields.insert("threshold", AsPercent(1.0 - bonsai_stat_fire_terror_base**level));
    fields.insert("damage", "+"..ceil(level * bonsai_stat_fire_terror_damage));
  }
}

class TFLV_Upgrade_Conflagration : TFLV_Upgrade_DotModifier {
  override TFLV_Upgrade_UpgradeElement Element() { return TFLV_Upgrade_ELEM_FIRE; }
  override string DotType() { return "TFLV_Upgrade_FireDot"; }

  override void ModifyDot(Actor player, Actor shot, Actor target, int damage, TFLV_Upgrade_Dot dot_item) {
    TFLV_Upgrade_FireDot(dot_item).spread = level;
  }

  override bool IsSuitableForWeapon(TFLV_WeaponInfo info) const {
    return HasMasteryPrereq(info, "TFLV_Upgrade_BurningTerror", "TFLV_Upgrade_InfernalKiln");
  }

  override void GetTooltipFields(Dictionary fields, uint level) {
    fields.insert("range", AsPercent(1.0 + level*0.5));
    fields.insert("softcap", ""..level);
  }
}

class TFLV_Upgrade_InfernalKiln : TFLV_Upgrade_ElementalUpgrade {
  override TFLV_Upgrade_UpgradeElement Element() { return TFLV_Upgrade_ELEM_FIRE; }
  double hardness;

  // Dealing damage to a burning enemy adds "kiln points" equal to 1% of the
  // amount of damage dealt times the number of stacks.
  override void OnDamageDealt(Actor player, Actor shot, Actor target, int damage) {
    let softcap = GetSoftcap(level);
    let hardcap = GetHardcap(level);
//    DEBUG("Kiln: hardness %f/%d", hardness, softcap);
    double bonus = TFLV_Upgrade_Dot.CountStacks(target, "TFLV_Upgrade_FireDot") * GetDamageFactor(level) * damage;
    if (hardness > softcap) {
      bonus *= 1.0 - double(hardness - softcap)/double(hardcap - softcap);
    }
//    DEBUG("Kiln: %f -> %f", hardness, hardness + bonus);
    hardness = min(hardcap, hardness + bonus);
  }

  override void Tick(Actor owner) {
    if (hardness > 0) hardness = max(0, hardness - 1.0/35.0);
  }

  override double ModifyDamageDealt(Actor pawn, Actor shot, Actor target, double damage, Name attacktype) {
    // Adds damage ranging from (upgrade level) to (upgrade level * 3)
    // depending on how much buff is stacked.
    if (hardness <= 0) return damage;
//    DEBUG("Kiln: %f + %f (%f)", damage, GetDamageBonus(level, hardness), hardness);
    return damage + GetDamageBonus(level, hardness);
  }

  override double ModifyDamageReceived(Actor pawn, Actor shot, Actor attacker, double damage, Name attacktype) {
    // Blocks damage up to level*2, and loses 1 second of time per 10 damage blocked.
    if (hardness <= 0) return damage;
    let block = GetBlock(level);
//    DEBUG("Kiln: %f - %f (%f)", damage, block, hardness);
    if (damage > block) {
      hardness = max(0, hardness - block/10.0);
      damage -= block;
    } else {
      hardness = max(0, hardness - (damage-1)/10.0);
      damage = 1;
    }
    return damage;
  }

  override bool IsSuitableForWeapon(TFLV_WeaponInfo info) const {
    return HasMasteryPrereq(info, "TFLV_Upgrade_BurningTerror", "TFLV_Upgrade_Conflagration");
  }

  static double GetDamageFactor(uint level) { return level*0.02; }
  static uint GetSoftcap(uint level) { return 5+level*5; }
  static uint GetHardcap(uint level) { return GetSoftcap(level)*2; }
  static uint GetDamageBonus(uint level, double hardness) {
    if (hardness <= 0) return 0;
    return ceil(level + level * hardness/GetSoftcap(level));
  }
  static uint GetBlock(uint level) { return level * 2; }

  override void GetTooltipFields(Dictionary fields, uint level) {
    fields.insert("hardness", AsPercent(GetDamageFactor(level)));
    fields.insert("softcap", AsSeconds(GetSoftcap(level)*35));
    fields.insert("hardcap", AsSeconds(GetHardcap(level)*35));
    fields.insert("damage", AsRange(GetDamageBonus(level, 1), GetDamageBonus(level, GetHardcap(level))));
    fields.insert("block", ""..GetBlock(level));
  }
}

class TFLV_Upgrade_FireDot : TFLV_Upgrade_Dot {
  bool burning;
  uint terror; // level of Searing Heat upgrade
  uint spread; // level of Conflagration upgrade

  override double GetElementMultiplier() { return bonsai_stat_fire_mult; }

  Default {
    DamageType "Fire";
  }

  override string GetParticleColour() {
    static const string hot[] = { "red", "orangered", "orange", "yellow", "lightyellow" };
    static const string cold[] = { "red4", "orangered4", "orange4", "orangered4", "red4" };
    if (burning)
      return hot[random[TFLV_Upgrade_RNG_FireColour](0,4)];
    else
      return cold[random[TFLV_Upgrade_RNG_FireColour](0,4)];
  }

  override double GetParticleZV() {
    return 0.1;
  }

  override double GetDamage() {
    double goal = owner.SpawnHealth() * bonsai_stat_fire_cutoff * bonsai_stat_fire_heat_factor ** (stacks-1);
    double total_damage = owner.health - goal;

    if (spread > 0)
      SpreadFlames();

    if (total_damage <= 0.0) {
      burning = false;
      if (terror && !owner.bNOFEAR) DoTerror(0);
      return 0.0;
    }

    burning = true;
    double damage = min(total_damage/10.0 + ceil(terror * bonsai_stat_fire_terror_damage)/5.0, stacks * bonsai_stat_fire_damage_per_stack);
    if (terror > 0 && !owner.bNOFEAR) DoTerror(damage);
    return damage;
  }

  // Burning Terror implementation.
  void DoTerror(double damage) {
    if (damage > 0.1 && !owner.bFRIGHTENED) {
      let missing_health = 1 - double(owner.health)/owner.SpawnHealth();
      if (missing_health >= bonsai_stat_fire_terror_base ** (stacks+terror)) {
        owner.bFRIGHTENED = true;
      }
    } else if (owner.bFRIGHTENED && frandom[TFLV_Upgrade_RNG_FireTerror](0.0, 1.0) > 0.95) {
      owner.bFRIGHTENED = false;
    }
  }

  // Conflagration implementation.
  // Drop a fire-spreading entity that sets everything around it on fire.
  void SpreadFlames() {
    let aux = TFLV_Upgrade_Conflagration_Aux(Spawn("TFLV_Upgrade_Conflagration_Aux", owner.pos));
    aux.target = self.target;
    aux.spread = self.spread;
    aux.stacks = self.stacks;
    aux.terror = self.terror;
    aux.range = owner.radius;
  }

  override void CopyFrom(TFLV_Upgrade_Dot _src) {
    super.CopyFrom(_src);
    let src = TFLV_Upgrade_FireDot(_src);
    self.terror = max(self.terror, src.terror);
    self.spread = max(self.spread, src.spread);
  }
}

class TFLV_Upgrade_Conflagration_Aux : Actor {
  double stacks;
  uint terror; // level of Burning Terror upgrade
  uint spread; // level of Conflagration upgrade
  uint range; // radius of parent actor

  Default {
    RenderStyle "Translucent";
    Alpha 0.4;
    +NODAMAGETHRUST;
    +NOGRAVITY;
  }

  override void PostBeginPlay() {
//    DEBUG("conflagration running");
    self.SetStateLabel("Spawn");
  }

  uint GetRange() {
//    DEBUG("GetRange: %d", 32 + spread*16 + stacks);
    return range * (1.0 + 0.5*spread + 0.1*stacks);
  }

  void SpreadTo(Actor target) {
    let fdot = TFLV_Upgrade_FireDot(TFLV_Upgrade_Dot.GiveStacks(self.target, target, "TFLV_Upgrade_FireDot", 0, 1));
    if (fdot.stacks < self.stacks) {
      fdot.AddStacks(1, spread);
//      DEBUG("Transfer: %s with softcap %d -> %.1f stacks", TAG(target), spread, fdot.stacks);
    }
    fdot.terror = max(fdot.terror, self.terror);
    fdot.spread = max(fdot.spread, self.spread - 1);
  }

  void Ignite() {
    Array<Actor> targets;
    TFLV_Util.MonstersInRadius(self, GetRange(), targets);
    for (uint i = 0; i < targets.size(); ++i) {
      SpreadTo(targets[i]);
    }
  }

  States {
    Spawn:
      LFIR G 7 NoDelay Ignite();
      LFIR H 7;
      STOP;
  }
}
