// #namespace TFLV::Upgrade;
// #debug off;

class TFLV_Upgrade_HomingShots : TFLV_Upgrade_BaseUpgrade {
  override void OnProjectileCreated(Actor player, Actor shot) {
    shot.bSEEKERMISSILE = true;
    // shot.bSCREENSEEKER = true;
    let aux = TFLV_Upgrade_HomingShots_Aux(shot.GiveInventoryType("TFLV_Upgrade_HomingShots_Aux"));
    aux.level = level;
    aux.SetStateLabel("Homing");
  }

  override bool IsSuitableForWeapon(TFLV_WeaponInfo info) const {
    return info.IsSlowProjectile() && info.upgrades.Level("TFLV_Upgrade_HomingShots") < 12;
  }

  override void GetTooltipFields(Dictionary fields, uint level) {
    uint range_per_level = bonsai_stat_homing_base_range;
    uint base = bonsai_stat_homing_base_range;
    fields.insert("lock-range", AsMeters(min(ceil((base + level*range_per_level)/128.0), 8)*128));
    fields.insert("homing-range", AsMeters(base+level*range_per_level));
    fields.insert("dps", string.format("%d", ceil(min(level, 90) * bonsai_stat_homing_turn_rate)*35/2));
  }
}

class TFLV_Upgrade_HomingShots_Aux : Inventory {
  uint level;

  States {
    Homing:
      TNT1 A 0 DoHoming();
      TNT1 A 2;
      LOOP;
  }

  bool TerminalHoming() {
    uint range = bonsai_stat_homing_base_range + level * bonsai_stat_homing_base_range;
    return owner.tracer
      && owner.CheckLOF(
          0, // flags
          range,
          0, // minrange
          0, 0, // angles
          0, 0, // offset
          AAPTR_TRACER);
  }

  void DoHoming() {
    if (!owner) {
      Destroy();
      return;
    }
    uint range = bonsai_stat_homing_base_range + level * bonsai_stat_homing_base_range;
    if (!TerminalHoming()) {
      owner.tracer = null;
      let vel = owner.vel;
      let angle = owner.angle;
      owner.A_SeekerMissile(
        0,
        1,
        SMF_LOOK | SMF_PRECISE | SMF_CURSPEED,
        min(level*256, 256),
        min(ceil(range/128.0), 8));
      owner.vel = vel;
      owner.angle = angle;
    } else {
      owner.A_SeekerMissile(
        0,
        ceil(min(level, 90) * bonsai_stat_homing_turn_rate),
        SMF_PRECISE | SMF_CURSPEED);
    }
  }
}
