// #namespace TFLV::Upgrade;

class TFLV_Upgrade_Submunitions : TFLV_Upgrade_BaseUpgrade {
  override TFLV_Upgrade_UpgradePriority Priority() { return TFLV_Upgrade_PRI_EXPLOSIVE; }

  override void OnKill(PlayerPawn player, Actor shot, Actor target) {
    if (shot is "TFLV_Upgrade_Submunitions_Grenade") return;
    let aux = TFLV_Upgrade_Submunitions_Spawner(target.Spawn("TFLV_Upgrade_Submunitions_Spawner", target.pos));
    aux.weaponspecial = Priority();
    aux.target = player;
    let count = bonsai_stat_submunitions_base+level;
    aux.ReactionTime = count;
    aux.damage = ((target.SpawnHealth() + abs(target.health)) * (1.0 - bonsai_stat_submunitions_health_scale ** level))/count + bonsai_stat_submunitions_bonus_damage*level;
    aux.blast_radius = target.radius*2.5;
    aux.ttl = ceil(level*5 * bonsai_stat_submunitions_lifetime); // in seconds
  }

  override bool IsSuitableForWeapon(TFLV_WeaponInfo info) const {
    return !info.IsMelee();
  }

  override void GetTooltipFields(Dictionary fields, uint level) {
    fields.insert("count", ""..(bonsai_stat_submunitions_base + level));
    fields.insert("bonusdamage", ""..(level * bonsai_stat_submunitions_bonus_damage));
    fields.insert("damage", AsPercent(1.0 - bonsai_stat_submunitions_health_scale ** level));
    fields.insert("ttl", AsSeconds(ceil(level*5 * bonsai_stat_submunitions_lifetime)*35));
  }
}

class TFLV_Upgrade_Submunitions_Spawner : Actor {
  uint damage;
  uint blast_radius;
  uint ttl;

  States {
    Spawn:
      TNT1 A 7;
    SpawnMunition:
      TNT1 A 1 SpawnMunition();
      TNT1 A 0 A_CountDown();
      LOOP;
  }

  void SpawnMunition() {
    let aux = TFLV_Upgrade_Submunitions_Grenade(A_SpawnProjectile(
      "TFLV_Upgrade_Submunitions_Grenade", 32, 0, random[TFLV_Upgrade_RNG_GrenadeAngle](0,360),
      CMF_AIMDIRECTION|CMF_ABSOLUTEANGLE));
    aux.weaponspecial = weaponspecial;
    aux.target = target;
    aux.damage = damage;
    aux.blast_radius = blast_radius;
    aux.ReactionTime = ttl*5 + random[TFLV_Upgrade_RNG_GrenadeTimer](0,5); // bomblets tick 5 times a second, so multiply by 5
//    DEBUG("Created submunition: level=%d power=%d",
//      aux.level, aux.damage);
  }
}

class TFLV_Upgrade_Submunitions_Grenade : Actor {
  uint damage;
  uint blast_radius;
  property UpgradePriority: weaponspecial;

  Default {
    TFLV_Upgrade_Submunitions_Grenade.UpgradePriority TFLV_Upgrade_PRI_EXPLOSIVE;
    Radius 12;
    Height 24;
    Speed 15;
    Scale 0.4;
    PainType "Extreme";
    Projectile;
    // +FLOORHUGGER;
    +SEEKERMISSILE;
    +NODAMAGETHRUST;
    -NOGRAVITY;
    BounceType "Grenade";
    BounceFactor 1.0;
  }

  override int DoSpecialDamage(Actor target, int damage, Name damagetype) {
    if (target == self.target) {
      return 1;
    }
    return damage;
  }

  States {
    Spawn:
      LSUB DCBA 7 A_CountDown();
      LOOP;
    Death:
      BNFX A 0 A_Explode(damage, blast_radius, XF_NOSPLASH, false, blast_radius);
      BNFX A 0 A_AlertMonsters();
      BNFX A 0 A_StartSound("bonsai/smallboom", CHAN_WEAPON, CHANF_OVERLAP, 1, 0.5);
      BNFX A 0 A_StartSound("bonsai/smallboom", CHAN_7, CHANF_OVERLAP, 0.1, 0.01);
      BNFX ABC 7 Bright;
      STOP;
  }
}
