// #namespace TFLV::Upgrade;
// #debug off;

class TFLV_Upgrade_Thorns : TFLV_Upgrade_BaseUpgrade {
  TFLV_Upgrade_Thorns_Aux aux;

  override void OnDamageReceived(Actor pawn, Actor shot, Actor attacker, int damage) {
    if (!attacker || pawn == attacker || !attacker.bISMONSTER || attacker.bFRIENDLY) return;
    // Create once and keep it around.
    if (!aux) aux = TFLV_Upgrade_Thorns_Aux(pawn.Spawn("TFLV_Upgrade_Thorns_Aux"));
    aux.Retaliate(pawn, level, attacker, damage);
  }

  override bool IsSuitableForPlayer(TFLV_PerPlayerStats stats) const {
    return true;
  }

  override void GetTooltipFields(Dictionary fields, uint level) {
    fields.insert("min-range", AsMeters(bonsai_stat_thorns_min_range*level));
    fields.insert("max-range", AsMeters(bonsai_stat_thorns_max_range*level));
    let elem_threshold = 1 - 0.9/level;
    fields.insert("elem-proc-range", AsMeters(bonsai_stat_thorns_min_range*level + elem_threshold * (bonsai_stat_thorns_max_range*level - bonsai_stat_thorns_min_range*level)));
  }
}

// We have a special actor for actually inflicting the thorns damage so that we
// can set its weaponspecial field according to whether we want thorns retaliation
// to proc elemental effects or not.
class TFLV_Upgrade_Thorns_Aux : Actor {
  property UpgradePriority: weaponspecial;

  Default {
    RenderStyle "None";
    +NOBLOCKMAP;
    +NOGRAVITY;
  }

  void Retaliate(Actor player, uint level, Actor attacker, int damage) {
    let range = player.Distance3D(attacker);
    double min_radius = bonsai_stat_thorns_min_range*level;
    double max_radius = bonsai_stat_thorns_max_range*level;
    if (max_radius < range) return;
    double multiplier = (1 - max(0, range-min_radius)/(max_radius-min_radius));
    self.weaponspecial = multiplier >= 0.9/level ? TFLV_Upgrade_PRI_THORNS : TFLV_Upgrade_PRI_NULL;
    attacker.DamageMobj(self, player,
      max(level, damage * (level+1) * multiplier), "Thorns", DMG_THRUSTLESS);
  }
}
