// TooltipOptionMenu.zsc
// Drop-in replacement for OptionMenu with tooltip support.

class TFLV_TooltipOptionMenu : OptionMenu {
  mixin TFLV_TooltipMenu;

  void InitDynamic(Menu parent, OptionMenuDescriptor desc) {
    desc.mItems.Clear();
    self.tooltip_settings = GetDefaults();
    super.Init(parent, desc);
  }

  override void Init(Menu parent, OptionMenuDescriptor desc) {
    super.Init(parent, desc);
    self.tooltip_settings = GetDefaults();
    if (desc.mItems.size() == 0) return;

    let tail = OptionMenuItemTFLV_TooltipHolder(desc.mItems[desc.mItems.size()-1]);
    if (tail) {
      tooltips.copy(tail.tooltips);
      return;
    }

    MenuItemBase selected = null;
    if (desc.mSelectedItem >= 0 && desc.mSelectedItem < desc.mItems.size())
      selected = desc.mItems[desc.mSelectedItem];

    array<OptionMenuItem> items;
    items.Move(desc.mItems);

    int  startblock   = -1;
    bool tooltip_mode = true;

    for (int i = 0; i < items.size(); ++i) {
      if (items[i] is "OptionMenuItemTFLV_TooltipID") {
        TooltipID(OptionMenuItemTFLV_TooltipID(items[i]).mod_id);
      } else if (items[i] is "OptionMenuItemTFLV_Tooltip") {
        let tt = OptionMenuItemTFLV_Tooltip(items[i]);
        if (tt.tooltip == "" && !tooltip_mode) {
          startblock = desc.mItems.size();
        } else {
          AddTooltip(startblock, desc.mItems.size()-1, tt.tooltip);
          tooltip_mode = true;
        }
      } else if (items[i] is "OptionMenuItemTFLV_TooltipGeometry") {
        OptionMenuItemTFLV_TooltipGeometry(items[i]).CopyTo(tooltip_settings);
      } else if (items[i] is "OptionMenuItemTFLV_TooltipAppearance") {
        OptionMenuItemTFLV_TooltipAppearance(items[i]).CopyTo(tooltip_settings);
      } else {
        if (tooltip_mode) {
          startblock   = desc.mItems.size();
          tooltip_mode = false;
        }
        desc.mItems.push(items[i]);
      }
    }

    desc.mItems.push(OptionMenuItemTFLV_TooltipHolder(
        new("OptionMenuItemTFLV_TooltipHolder").Init(tooltips)));

    if (selected) {
      for (int i = 0; i < desc.mItems.size(); ++i) {
        if (desc.mItems[i] == selected) { desc.mSelectedItem = i; break; }
      }
    }
  }
}

class OptionMenuItemTFLV_TooltipHolder : OptionMenuItem {
  mixin TFLV_TooltipHolder;
}

class OptionMenuItemTFLV_Tooltip : OptionMenuItem {
  mixin TFLV_TooltipItem;
}

class OptionMenuItemTFLV_TooltipGeometry : OptionMenuItem {
  mixin TFLV_TooltipGeometry;
}

class OptionMenuItemTFLV_TooltipAppearance : OptionMenuItem {
  mixin TFLV_TooltipAppearance;
}

class OptionMenuItemTFLV_TooltipID : OptionMenuItem {
  string mod_id;
  string menu_page;

  Object Init(string mod_id, string menu_page = "") {
    self.mod_id    = mod_id;
    self.menu_page = menu_page;
    return self;
  }

  override bool Selectable() { return false; }
}
