// #namespace TFLV::Upgrade;
// #debug off;

class TFLV_Upgrade_Cleave : TFLV_Upgrade_BaseUpgrade {
  override void OnKill(PlayerPawn pawn, Actor shot, Actor target) {
    let radius = 128; // 4m, twice chainsaw range and 2/3rds of nominal melee range
    if (pawn.Distance3D(target) > radius) return;
    // Find all potential targets in melee range of player
    Array<Actor> targets;
    TFLV_Util.MonstersInRadius(pawn, radius, targets);
    for (uint i = 0; i < targets.size(); ++i) {
      if (!targets[i] || targets[i] == target) continue;
//      DEBUG("Range to target %s is %f and it has %d health",
//        TAG(targets[i]), target.Distance3D(targets[i]), targets[i].health);
      TFLV_Upgrade_Cleave_Aux aux = TFLV_Upgrade_Cleave_Aux(pawn.Spawn("TFLV_Upgrade_Cleave_Aux"));
      aux.hit(pawn, targets[i], ceil(
          targets[i].SpawnHealth() * HealthMultiplier(level)
          + abs(target.health) * OverkillMultiplier(level)));
      break;
    }
  }

  double OverkillMultiplier(uint level) {
    return 1.0 + level * bonsai_stat_cleave_overkill;
  }
  // Scales from (1 - cap_base^1)*cap up to cap as levels increase
  double HealthMultiplier(uint level) {
    return (1.0 - 0.8 ** level) * bonsai_stat_cleave_health_cap;
  }

  override bool IsSuitableForWeapon(TFLV_WeaponInfo info) const {
    return info.IsMelee();
  }

  override void GetTooltipFields(Dictionary fields, uint level) {
    fields.insert("healthpct", AsPercent(HealthMultiplier(level)));
    fields.insert("overkillpct", AsPercent(OverkillMultiplier(level)));
  }
}

class TFLV_Upgrade_Cleave_Aux : Actor {
  void hit(Actor source, Actor target, uint damage) {
//    DEBUG("Cleaving %s for %d damage", TAG(target), damage);
    target.DamageMobj(self, source, damage, "Melee", DMG_INFLICTOR_IS_PUFF|DMG_PLAYERATTACK);
  }
}
